version: "3.8"

services:
  zookeeper:
    image: confluentinc/cp-zookeeper:latest
    environment:
      ZOOKEEPER_CLIENT_PORT: 2181
      ZOOKEEPER_TICK_TIME: 2000
    networks:
      test-core-banking_corebanking-network:
        aliases:
          - zookeeper

  kafka:
    image: confluentinc/cp-kafka:latest
    depends_on:
      - zookeeper
    ports:
      - 9092:9092
    environment:
      KAFKA_BROKER_ID: 1
      KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181
      KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://kafka:29092,PLAINTEXT_HOST://kafka:9092
      KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: PLAINTEXT:PLAINTEXT,PLAINTEXT_HOST:PLAINTEXT
      KAFKA_INTER_BROKER_LISTENER_NAME: PLAINTEXT
      KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 1
    networks:
      test-core-banking_corebanking-network:
        aliases:
          - kafka

  kafka-manager:
    image: hlebalbau/kafka-manager:latest
    depends_on:
      - kafka
    ports:
      - 9091:9000
    environment:
      ZK_HOSTS: "zookeeper:2181"
    networks:
      test-core-banking_corebanking-network:
        aliases:
          - kafka-manager

networks:
  test-core-banking_corebanking-network:
    external: true
